version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Build image
          command: | 
            docker build -t quasar-notify .
      - run:
          name: Docker login
          command: |
            docker login $CONTAINER_REGISTRY -u $CONTAINER_REGISTRY_USERNAME -p $CONTAINER_REGISTRY_PASSWORD
      - run:
          name: Push image if commit is tagged or if branch is master
          command: |
            TAG=$(git describe --tags --match "v*")
            IMAGE_URL=${CONTAINER_REGISTRY}/quasar-notify:${TAG}
            if [[ "$CIRCLE_BRANCH" == "master" || ! -z "$CIRCLE_TAG" ]]; then
                echo "tag = $TAG"
                docker tag quasar-notify $IMAGE_URL
                docker push $IMAGE_URL
            fi

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: vanoord
          filters:
            tags:
              only: /.*/
      # - publish:
      #     requires:
      #       - build
      #     context: vanoord
      #     filters:
      #       tags:
      #         only: /^v.*/